FROM alpine:3.6
RUN apk add --no-cache bash python python-dev openssl-dev py-pip py-mysqldb alpine-sdk
RUN pip install pip --upgrade
RUN pip install grpcio
RUN pip install nose

WORKDIR /kama
COPY . .
RUN pip install .
