FROM alpine:3.6
RUN apk add --no-cache \
  bash \
  python \
  python-dev \
  openssl-dev \
  py-pip \
  py-mysqldb \
  alpine-sdk

WORKDIR /kama

RUN pip install pip --upgrade

COPY requirements.txt .

RUN pip install -r requirements.txt \
    && pip install nose

COPY . .

RUN pip install .
